#
GET http://localhost:7373/api/v1/addresses?country=DE&page=5&size=10&region=NorthEast

###

GET http://localhost:7373/api/v1/addresses

###
GET http://localhost:7373/api/v1/addresses?country=%

###
POST http://localhost:7373/api/v1/addresses
Content-Type: application/json

{
  "number": "1",
  "street": "Dacia",
  "zipCode": "0001",
  "city": "Bucharest",
  "region": "Ilfov",
  "department": "Sud",
  "country": "RO"
}

###