POST  localhost:7373/api/v1/patients
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "medicalId": "1-MEDICALID",
  "nationalId": "2-NATIONALID",
  "birthDate": "2021-12-30T23:59:59.000Z"
}

###

GET localhost:7373/api/v1/patients
Content-Type: application/json

###

### please provide PATIENT_UUID, e.g. 3bc9b545-08d8-495a-8cf4-a000ac11723d
GET localhost:7373/api/v1/patients/{PATIENT_UUID}
Content-Type: application/json
